language: java
jdk:
- openjdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: "jhviyI97Is9w9gul/7cNsVcNeEWChbDJ1m0kYy/lj+5bLzk72oOdpAkIpRtKyVNWd31JgDLIxD0i51ysdgPIC0iA0wvxs/rz8KM9UVYLDKR3//4R8EDCi7ekid6NBSABmUmjPAW8d+Y+BP2RaSQj5QE9V64Z/eRriV9QJj5QqA/JJITYfbZTNAxbZKgd3qcozWAIrpWaU+cO21nRgzUgNY/k377lEzQMRkwZv4zsN8OkDEKBmVorNU2kKTJ7hNbHbx2lSEMnqIv8F2IrBVklr0yrDT3XH5dlfvcTNvCzYUzi8YoxnERpjkznPSq6Pj3W+s4hpZAEHAoy5yFDbBnBDYTxzjKLkyOEKvBq0avBzwHxitMsoWe8YYOni1MLI2BMINtTiGpThN2K/LcJO5beWTwOHXRstFcPs2hxHV31q6kEitQSuIAYz/0ScE3J7JfScNVRaHpNVHqoNC6RGse8yXfUZTwbXwlMZ5bNhYhIKk2THsyWe1WpTqYhxV0qGdJzxJuo5hyzNoxuPxS5e0XwW2nZO6zq41TlU1bp2tcrWcFdnH6fMnuoyzC4fkAgMox/epWivJFma+vz0/TnAd/x++/mYVRTdrTRA9pcRWyWilJFd5Bvw1PzruKTMDMU/W0y+3krto2Kd1Wr2+TRsVSSYZrByGMkHZsexGKnxeP4SiQ="
