language: java
jdk:
- openjdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
deploy:
  api_key:
    secure: "Bes++4CWQbKM1Yt9o1S08Hiima795NeTcR/GGRuk2m+bPaWLK1WAXFW/UIbe7FTdNQWJprjINyrxgZeQ00ABar5nG8/YgAt1zZ8gQuheDhErvkwSNuKv68LOhi+ZYIia4shZE9Us18eCxnSFEAOko0tKxpaApJ6rVYFW8f4YPgf9R4GXKIMc5FihFUsc7nGgvq2OAAIUArCLREL9MTGsAW2WQNuGQV6g7Q8bLeIdFcLLrnajN1tbtVmVGYGGx+10AikrauYIioYA5/3Ny8Odp7r3pYqefDLLzd+g1YYz5Y/sMY4e0uPDH82WUL9aIqnehoLCWvLAdqBG+odGL5SywYhDZF/tdswYiQ6MnEVGiw6wbRjedAWpYqxfw5qIMD4bhM6+9BwkZcQsAMrtzviBnZU66WICqIDezK0sqAr16Sfc+LfLzgr+ABm1USZ629Jd+1eTqXnZjBbXqrGJlyjbzCTpIhMLYkn4Q/XCRkyZHEZVYOTDTL63+svnJGwtG0YWqku5oATAwnt26HnwtdwtXTTBND9sALs+bG8ZenlsYY95+KABHhkFBmBTH16CoIiKxwuXpIi8/0hxXlUhL4PK2K1qLgUxV1BiRIeHgLp6dJs+/ZtO+PWFO5VPiuMPLTXI7ck8Qz+d1KC8I/DzO0CE77IhGDVKbYJb7gu0ZYgoRFU="