spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myap
    username: postgres
    password: postgres
  jpa:
    hibernate:
      dll-auto: none
    properties:
      hibernate.hbm2ddl.auto: create-drop

server:
  port: 8090
